### ISSUE TITLE
compiling problem on esp32

### ISSUE THREAD

**Issue by simonecable** [rkubera/ESP8266-RC-Transmitter-Receiver#1]
I tried to compiling it with arduino IDE 1.8.12, and load it on a esp32 dev kit1, Servo library was not recognizable so i change it with ESP32_Servo.h, so the esp2866 tx rx.ino was compiled, RSSI.ino compiled too, but rx.ino give me that error:
rx_udp_uart.write(my_message, my_size);

invalid conversion from 'char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]

so i can't compile the rest and load it, are you so kind to help me or let me know what is the problem?

**Comment by rkubera** [comment]
esp32 is no tsupported yet.
