### ISSUE TITLE
LTE 

### ISSUE THREAD

**Issue by jpfree** [rkubera/ESP8266-RC-Transmitter-Receiver#2]
thanks for your big share ,
it's a wifi lan network?
how to transmitted  SBUs/ppm/pwm signal be through 4G network card and public ip vps?
thank you..

**Comment by rkubera** [comment]
Yes, my software uses wifi connection only.
4G is not supported and not recommended - there may be lags in transmission and inverted UDP packages order.
Regards,
Radek.
